### ISSUE TITLE
LED blink code for errors?

### ISSUE THREAD

**Issue by beniroquai** [Matchboxscope/Matchboxscope#20]
Someone mentioned, it would be good to have a blink-code to see if the device is still operational. 
@ethanjli what do you think is a good strategy when the device wakes up after deep sleep? 

We have the Flashlight that will blink 25x in case we do Z-stacking..enough? Or perhaps have SOS in case something is wrong? ;-)

**Comment by ethanjli** [comment]
I guess it depends on what kind of information would be useful to get after the device wakes. If all you need to know is "is the device still saving images as usual?", maybe it'd make sense to just turn on or flash the LED for some recognizable duration after each successful image capture+save step.
