### ISSUE TITLE
Dont 3D print in light colors

### ISSUE THREAD

**Issue by Jerzeek** [Matchboxscope/Matchboxscope#26]
I used Orange PETG Prusament (https://www.prusa3d.com/product/prusament-petg-prusa-orange-1kg/) But I found there is too much light leakage.
Please recommend others to print with dark-colored filament

**Comment by beniroquai** [comment]
That's indeed true. I only ever use black material. Where should I put it? Here? https://matchboxscope.github.io/docs/Matchboxscope#3d-printing-files

**Comment by Vsaggiomo** [comment]
added the warning in the instructions, thanks :)
