### ISSUE TITLE
As per request heres my serial log :)

### ISSUE THREAD

**Issue by Jordvl** [Matchboxscope/Matchboxscope#27]
[esp-web-tools-logs (2).txt](https://github.com/Matchboxscope/Matchboxscope/files/11353536/esp-web-tools-logs.2.txt)

**Comment by beniroquai** [comment]
Haha, the idea of filing an issue is to share your problem with the world :D 

But ok, I guess I resolved the issue in the latest version of code. I'll start the compile + upload action so that you can try flashing it through the web flashing tool :) 

Can you give it a try please?

**Comment by Jordvl** [comment]
I just packed my stuff can i do it tomorrow 😅

**Comment by beniroquai** [comment]
In Germany it's holiday. So: Yes of course!!

Am Mo., 1. Mai 2023 um 16:43 Uhr schrieb Jordvl ***@***.***>:

**Comment by beniroquai** [comment]
Done?
